/*Creación de tablas*/
CREATE TABLE "DEVJAVA".TIPOS_CUENTA (ID INTEGER, TIPO_DE_CUENTA VARCHAR2(255), DESCRIPCION VARCHAR(255), INTERES DECIMAL(10,2));

CREATE TABLE "DEVJAVA".SUCURSAL (SUCURSALID INTEGER, NOMBRE VARCHAR(255), DIRECCION VARCHAR(255), TELEFONO VARCHAR(50), HORA_INICIO DATE, HORA_FIN DATE );

CREATE TABLE "DEVJAVA".TIPO_TRANSACCION (ID INTEGER, TIPO_TRANSACCION VARCHAR(255));

CREATE TABLE "DEVJAVA".TIPO_DOCUMENTO (ID INTEGER, TIPO_DOCUMENTO VARCHAR(255));

CREATE TABLE "DEVJAVA".TRANSACCION (ID INTEGER, SUCURSAL_ID INTEGER, CODIGO_TRANSACCION VARCHAR(255), TIPO_TRANSACCION_ID INTEGER, CUENTA_ID INTEGER, VALOR FLOAT, FECHA DATE, ESTADO VARCHAR(50));

CREATE TABLE "DEVJAVA".CUENTA (ID INTEGER, TIPO_CUENTA_ID INTEGER, CLIENTE_ID INTEGER, SALDO FLOAT, FECHA_CREACION DATE);

CREATE TABLE "DEVJAVA".USUARIO (ID INTEGER, NOMBRES VARCHAR(255), APELLIDOS VARCHAR(255), TIPO_DOCUMENTO_ID INTEGER, NUMERO_DOCUMENTO VARCHAR(255), EMAIL VARCHAR(255), DIRECCION VARCHAR(255), ROL_ID INTEGER, TELEFONO VARCHAR(50), FECHA_CREACION DATE, FECHA_ACTUALIZACION DATE );

CREATE TABLE "DEVJAVA".ROL (ID INTEGER, NAME VARCHAR(255));

/*Constrain*/
/*Primary key*/

ALTER TABLE USUARIO  ADD CONSTRAINT pk_cliente PRIMARY KEY (ID);

ALTER TABLE CUENTA ADD CONSTRAINT pk_cuenta PRIMARY KEY (ID);

ALTER TABLE SUCURSAL ADD CONSTRAINT pk_sucursal PRIMARY KEY (SUCURSALID);

ALTER TABLE TIPOS_CUENTA ADD CONSTRAINT pk_tipos_cuenta PRIMARY KEY (ID);

ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT pk_tipo_documento PRIMARY KEY (ID);

ALTER TABLE TIPO_TRANSACCION ADD CONSTRAINT pk_tipo_transaccion PRIMARY KEY (ID);

ALTER TABLE TRANSACCION ADD CONSTRAINT pk_transaccion PRIMARY KEY (ID);

ALTER TABLE ROL ADD CONSTRAINT pk_rol PRIMARY KEY (ID);

/*Foreing key*/
ALTER  TABLE USUARIO  ADD CONSTRAINT fk_tipo_documento FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES TIPO_DOCUMENTO(ID);
ALTER  TABLE USUARIO  ADD CONSTRAINT fk_rol_id FOREIGN KEY (ROL_ID) REFERENCES ROL(ID);

ALTER TABLE CUENTA ADD CONSTRAINT fk_tipo_cuenta FOREIGN KEY (TIPO_CUENTA_ID) REFERENCES TIPOS_CUENTA(ID);
ALTER TABLE CUENTA ADD CONSTRAINT fk_cliente_id FOREIGN KEY (CLIENTE_ID) REFERENCES USUARIO(ID);

ALTER TABLE TRANSACCION ADD CONSTRAINT fk_sucursal FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSALID);
ALTER TABLE TRANSACCION ADD CONSTRAINT fk_tipo_transaccion FOREIGN KEY (TIPO_TRANSACCION_ID) REFERENCES TIPO_TRANSACCION(ID);
ALTER TABLE TRANSACCION ADD CONSTRAINT fk_cuenta FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID);

/*Valores positivos*/
ALTER TABLE CUENTA ADD CONSTRAINT check_salario CHECK (SALDO >= 0);
ALTER TABLE TIPOS_CUENTA ADD CONSTRAINT check_interes CHECK (INTERES >= 0 AND INTERES <= 1);

ALTER TABLE TRANSACCION  ADD CONSTRAINT check_valor CHECK (VALOR >= 0);

/*Números de celular*/
ALTER TABLE USUARIO ADD CONSTRAINT check_telefono CHECK (LENGTH(TELEFONO) = 10);

/*Email único*/
ALTER TABLE USUARIO ADD CONSTRAINT check_email UNIQUE (EMAIL);