BEGIN
	DECLARE
		rcTELEPHONE_COMPANY PCK_TELEPHONE_COMPANIES.t_TELEPHONE_COMPANY;
	BEGIN
		PCK_TELEPHONE_COMPANIES.findTelephoneCompany(1, rcTELEPHONE_COMPANY);
		
		DBMS_OUTPUT.PUT_LINE(rcTELEPHONE_COMPANY.NAME);
	END;
	
END;

BEGIN
	DECLARE
		op_TelephoneCompany TYRC_TELEPHONE_COMPANY;
	BEGIN
		PCK_APP_CREATE_TELEPHONE_COMPANY.findTelephoneCompany(1, op_TelephoneCompany);
		
		DBMS_OUTPUT.PUT_LINE(op_TelephoneCompany.NAME);
	END;
	
END;

BEGIN
	DECLARE
	subtype rcTELEPHONE_CALL IS TELEPHONE_CALLS%rowtype;
	type tb_TELEPHONE_CALL IS TABLE OF rcTELEPHONE_CALL INDEX BY binary_integer;
	id NUMBER;

	CURSOR cuTELEPHONE_COMPANY IS
		SELECT /*+LEADING(tc tcu)*/ tc.ID_TELEPHONE_CALL  FROM TELEPHONE_CALLS tc 
		INNER JOIN TELEPHONE_COMPANY_USERS tcu ON tc.ID_TELEPHONE_COMPANY_USER = tcu.ID_TELEPHONE_COMPANY_USER 
		WHERE tcu.ID_TELEPHONE_COMPANY = 1; 

	BEGIN
		OPEN cuTELEPHONE_COMPANY;
		FETCH cuTELEPHONE_COMPANY INTO id;
		CLOSE cuTELEPHONE_COMPANY;
		DBMS_OUTPUT.PUT_LINE(id);
	END;

END;

BEGIN 
	DECLARE
		rcTELEPHONE_CALL PCK_TELEPHONE_CALLS.t_tbTELEPHONE_CALL;
		id NUMBER;
	BEGIN
		PCK_TELEPHONE_CALLS.getTelephoneCallsByCompany(1, 'PENDING', rcTELEPHONE_CALL);
		id := rcTELEPHONE_CALL(1).ID_TELEPHONE_CALL;
		DBMS_OUTPUT.PUT_LINE( rcTELEPHONE_CALL.COUNT);
	END;
END;


 



